export const STRING_CONSTANTS = {
    REGISTRATION_SUCCESS : 'Registration success',
    REGISTRATION_ERROR : 'Registration error',
    LOGIN_SUCCESS : 'Login success',
    LOGIN_ERROR : 'Login error',
    EXIST : 'already exist',
    INVALID_CREDENTIALS : 'Invalid credentials',
    INVALID_PASSWORD : 'Incorrect password',
    INVALID_INPUT : 'Invalid input',
    LOGOUT_SUCCESS : 'Logout successfully',
    LOGOUT_ERROR : 'Logout failed',
    TOKEN_ISSUED : 'Token issued',
    TOKEN_ISSUE_ERROR : 'Token issuing failed',
    DATA_NOT_FOUND : 'Data not found' ,
    LOADING_SUCCESS : 'Loading data successfull',
    LOADING_ERROR : 'Loading data failed',
    UPDATION_SUCCESS : 'Updated data successfully',
    UPDATION_ERROR :'Updating data failed',
    CREATION_SUCCESS :'Created succesfully',
    CREATION_ERROR : 'Error saving data',
    DELETION_SUCCESS : 'Deleted successfully',
    DELETION_ERROR : 'Deletion failed',
    OTP_SENT : 'OTP sent to mail',
    OTP_SENT_ERROR : 'OTP sent failed',
    OTP_ERROR :'Invalid or expired OTP',
    RESET_OTP :'Password reset otp sent to your email',
    VERIFICATION_SUCCESS :'Verified successfully',
    VERIFICATION_ERROR : 'Verification failed',
    PASSWORD_RESET_SUCCESS : 'Password reset successfull',
    PASSWORD_RESET_ERROR : 'Password reset failed',
    GOOGLE_AUTH_SUCCESS : 'Google authentication successfull',
    GOOGLE_AUTH_ERROR : 'Google authentication failed',
    STATUS_PENDING : 'Verification status pending',
    BLOCKED : 'User blocked',
    UNBLOCKED :'User unblocked',
    SUCCESS : 'Success',
    SERVER : 'Server error',
    DRAFT_LIMIT : 'Draft limit exceeded',

}

export const DATABASE_FIELDS = {
    ID:'_id',
    NAME : 'name',
    FIRST_NAME : 'firstName',
    LAST_NAME : 'lastName',
    PASSWORD : 'password',
    EMAIL : 'email',
    PROFILE_IMAGE : 'profileImage',
    IS_ACTIVE : 'isActive',
    IS_VERIFIED : 'isVerified',
    IS_BLOCKED : 'isBlocked',
    IS_ADMIN_VERIFIED : 'isAdminVerified',
    EXPERTISE : 'expertise',
    EXPERIENCE : 'experience',
    BIO : 'bio',
    DOB :'dob',
    PHONE : 'phone',
    EARNINGS : 'earnings',
    STATUS : 'status',
    REASON : 'reason',
    ENROLLED_COURSES : 'enrolledCourses',
    TITLE : 'title',
    CATEGORY : 'category',

}
